spring:
  datasource:
    url: jdbc:mysql://192.168.89.128:3306/youtube_product?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

  cloud:
    nacos:
      server-addr: 192.168.89.128:8848
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

  redis:
    host: 192.168.89.128
    port: 6379
  rabbitmq:
    host: 192.168.89.128
    listener:
      simple:
        acknowledge-mode: manual
    publisher-confirm-type: correlated
    publisher-returns: true
  elasticsearch:
    rest:
      username: elastic
      password: 18718857472
      connection-timeout: 10s
      uris: 192.168.89.128:9200
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#  shardingsphere:
#    # 配置一写多读数据源
#    datasource:
#      names: writer,read1,read2
#      common:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        username: root
#        password: admin
#      writer:
#        type: com.zaxxer.hikari.HikariDataSource
#        jdbc-url: jdbc:mysql://192.168.89.128:3306/youtube_product?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
#        username: root
#        password: admin
#      read1:
#        type: com.zaxxer.hikari.HikariDataSource
#        jdbc-url: jdbc:mysql://192.168.89.128:4306/youtube_product?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
#        username: root
#        password: admin
#      read2:
#        type: com.zaxxer.hikari.HikariDataSource
#        jdbc-url: jdbc:mysql://192.168.89.128:5306/youtube_product?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
#        username: root
#        password: admin
#
#    rules:
#      replica-query:
#        data-sources:
#          product-r-w-split:
#            primary-data-source-name: writer
#            replica-data-source-names: read1,read2
#            load-balancer-name: ROUND_ROBIN
##        load-balancers:
##          product-r-balancer:
##            type: ROUND_ROBIN
#  main:
#    allow-bean-definition-overriding: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    icu.yujing: debug

seata:
  config:
    type: nacos
    nacos:
      server-addr: 192.168.89.128:8848
      namespace: d97ae271-b632-4464-bb1e-42a655c453bf
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    nacos:
      application: seata-server
      server-addr: 192.168.89.128:8848
      namespace: d97ae271-b632-4464-bb1e-42a655c453bf
      group: SEATA_GROUP
      username: nacos
      password: nacos

dubbo:
  application:
    name: product-service
    register-mode: instance
  registry:
    address: nacos://192.168.89.128:8848
  consumer:
    check: false